services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automotive-spark
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    command: >
      bash -c "
      tail -f /dev/null
      "
